import sys, importlib, time, json, math, os
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BACKEND = ROOT / "backend"
sys.path.insert(0, str(BACKEND))
EVD = ROOT / "evidence"
EVD.mkdir(exist_ok=True)

stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")

log_lines = []
def P(s):
    log_lines.append(str(s))
    print(s)

P_start = time.perf_counter()
P("== Nyaya Smoke / Evidence Runner ==")
P("")

MODULES = [
    ("settings", "nyaya.config.settings"),
    ("security", "nyaya.core.security"),
    ("database", "nyaya.core.database"),
    ("dbmodels", "nyaya.db.models.schema"),
    ("repositories", "nyaya.db.repositories.crud"),
    ("schemas_pydantic", "nyaya.schemas"),
    ("qdrant_client", "nyaya.services.qdrant_client"),
    ("redis_client", "nyaya.services.redis_client"),
    ("embeddings_meta", "nyaya.services.embeddings"),
    ("bm25_index", "nyaya.search.bm25_index"),
    ("dense_index_meta", "nyaya.search.dense_index"),
    ("hybrid_pipeline", "nyaya.search.hybrid"),
    ("kg_service", "nyaya.search.kg_service"),
    ("evaluation", "nyaya.evaluation"),
    ("seed_acts", "nyaya.seed.acts"),
    ("seed_sections", "nyaya.seed.sections"),
    ("seed_ipc_bns", "nyaya.seed.ipc_bns_mappings"),
    ("seed_kg_relations", "nyaya.seed.kg_relations"),
    ("seed_benchmark_questions", "nyaya.seed.benchmark_questions"),
]

REPORT = {"generated_at_utc": datetime.now(timezone.utc).isoformat(), "modules": {}, "schema": {}, "seed": {}, "metrics_smoke": {}, "hybrid_smoke": {}}

P("[1/5] Module imports:")
all_import_ok = True
for key, imp in MODULES:
    t = time.perf_counter()
    try:
        importlib.import_module(imp)
        dt = time.perf_counter() - t
        P(f"  OK   {dt:7.4f}s  {imp}")
        REPORT["modules"][key] = {"ok": True, "import": imp, "elapsed_seconds": round(dt, 4)}
    except Exception as e:
        all_import_ok = False
        dt = time.perf_counter() - t
        msg = f"{type(e).__name__}: {e}"
        P(f"  FAIL {dt:7.4f}s  {imp}  {msg}")
        REPORT["modules"][key] = {"ok": False, "import": imp, "elapsed_seconds": round(dt, 4), "error": msg}

P("")
P("[2/5] Seed counts:")
from nyaya.seed.acts import ACTS
from nyaya.seed.sections import SECTIONS
from nyaya.seed.ipc_bns_mappings import IPC_BNS_MAPPINGS
from nyaya.seed.kg_relations import KG_EDGES
from nyaya.seed.benchmark_questions import BENCHMARK_QUESTIONS

per_act = {}
for s in SECTIONS:
    per_act[s["act_short_title"]] = per_act.get(s["act_short_title"], 0) + 1

REQUIRED_SECTION_FIELDS = (
    "section_number", "title", "bare_text", "plain_language", "keywords",
    "punishments", "bailable", "cognizable", "compoundable",
    "source_page", "checksum_sha256",
)
# Check first 10 seed sections for required fields (id/act generated by loader)
missing_by_field = {}
for i, s in enumerate(SECTIONS[:10]):
    for field in REQUIRED_SECTION_FIELDS:
        if field not in s and field not in ("source_pdf",):
            # source_pdf may be inherited from Act; only flag if explicitly missing in all
            if field == "source_pdf":
                continue
            missing_by_field.setdefault(field, []).append(i)
schema_ok = len(missing_by_field) == 0
REPORT["schema"] = {
    "sampled_first_N": 10,
    "required_fields": list(REQUIRED_SECTION_FIELDS),
    "missing": {k: list(v) for k, v in missing_by_field.items()},
    "all_hard_constraints_satisfied": schema_ok,
}

seed_ok = (
    len(ACTS) == 10
    and len(SECTIONS) >= 51
    and len(IPC_BNS_MAPPINGS) >= 17
    and len(KG_EDGES) >= 15
    and len(BENCHMARK_QUESTIONS) >= 25
    and schema_ok
)

REPORT["seed"] = {
    "acts": {"count": len(ACTS), "expected": 10, "titles": [a["short_title"] for a in ACTS]},
    "sections": {"count": len(SECTIONS), "expected_min": 51, "per_act": per_act},
    "ipc_bns_pairs": {"seed_pairs": len(IPC_BNS_MAPPINGS), "bidirectional_after_load": len(IPC_BNS_MAPPINGS)*2,
                      "pairs_sample": IPC_BNS_MAPPINGS[:5]},
    "kg_edges": {"count": len(KG_EDGES), "types_sample": [e[4] for e in KG_EDGES[:10]]},
    "benchmark_questions": {"count": len(BENCHMARK_QUESTIONS), "expected_min": 25,
                            "difficulties": {}, "per_q_sample": [(q[2], q[0], q[1], len(q[3])) for q in BENCHMARK_QUESTIONS[:8]]},
    "passes_baseline_counts": seed_ok,
}
import collections
difficulty_counter = collections.Counter(q[1] for q in BENCHMARK_QUESTIONS)
REPORT["seed"]["benchmark_questions"]["difficulties"] = dict(difficulty_counter)
for k, v in [
    ("Acts", f"{len(ACTS)}/10"),
    ("Sections", f"{len(SECTIONS)}/>=51"),
    ("IPC-BNS pairs", f"{len(IPC_BNS_MAPPINGS)} → bidirectional {len(IPC_BNS_MAPPINGS)*2}"),
    ("KG edges", f"{len(KG_EDGES)}"),
    ("Benchmark questions", f"{len(BENCHMARK_QUESTIONS)}/>=25  (easy/medium/hard = {difficulty_counter.get('easy',0)}/{difficulty_counter.get('medium',0)}/{difficulty_counter.get('hard',0)})"),
    ("Schema hard constraints", "PASS" if schema_ok else f"FAIL missing: {list(missing_by_field.keys())}"),
]:
    P(f"  · {k:32s}  {v}")

P("")
P("[3/5] Metric math (synthetic ranked list):")
from nyaya.evaluation import recall_at_k, precision_at_k, reciprocal_rank

relevant = {2, 5, 9, 17, 21}
retrieved = [2, 55, 9, 3, 17, 8, 5, 10, 22, 4, 21, 30]
r5 = recall_at_k(relevant, retrieved, 5)
r10 = recall_at_k(relevant, retrieved, 10)
p10 = precision_at_k(relevant, retrieved, 10)
mrr = reciprocal_rank(relevant, retrieved)
EXPECTED = {"recall_at_5": 3/5, "recall_at_10": 4/5, "precision_at_10": 4/10, "mrr": 1.0}
validated_top10 = {2: True, 55: False, 9: True, 3: False, 17: True, 8: False, 5: True, 10: False, 22: False, 4: True}
hallucinated = sum(1 for rid in retrieved[:10] if rid not in relevant and validated_top10.get(rid, False) is False)
hall_q = 1.0 if hallucinated > 0 else 0.0
arithmetic_exact = (
    math.isclose(r5, EXPECTED["recall_at_5"]) and math.isclose(r10, EXPECTED["recall_at_10"])
    and math.isclose(p10, EXPECTED["precision_at_10"]) and math.isclose(mrr, EXPECTED["mrr"])
)

REPORT["metrics_smoke"] = {
    "relevant_ids": sorted(relevant),
    "retrieved_top12": retrieved,
    "results": {"recall_at_5": round(r5, 4), "recall_at_10": round(r10, 4), "precision_at_10": round(p10, 4), "mrr": round(mrr, 4), "hallucination_rate_for_q": round(hall_q, 4), "hallucinated_items_count": hallucinated},
    "expected": {k: round(v, 4) for k, v in EXPECTED.items()},
    "arithmetic_exact_match": arithmetic_exact,
    "notes": "ID #5 is 7th but falls within top 10 → Recall@10 = 4/5 (IDs 2,9,17,5 in top 10), MRR = 1.0 because the first result (#2) is relevant.",
}
P(f"  Recall@5    = {r5:.4f}   expected {EXPECTED['recall_at_5']:.4f}   → {'✓' if math.isclose(r5, EXPECTED['recall_at_5']) else '✗'}")
P(f"  Recall@10   = {r10:.4f}   expected {EXPECTED['recall_at_10']:.4f}   → {'✓' if math.isclose(r10, EXPECTED['recall_at_10']) else '✗'}")
P(f"  Precision@10= {p10:.4f}   expected {EXPECTED['precision_at_10']:.4f}   → {'✓' if math.isclose(p10, EXPECTED['precision_at_10']) else '✗'}")
P(f"  MRR         = {mrr:.4f}   expected {EXPECTED['mrr']:.4f}   → {'✓' if math.isclose(mrr, EXPECTED['mrr']) else '✗'}")
P(f"  Hallucination(q-level) = {hall_q:.4f}, hallucinated items = {hallucinated}")
P(f"  Arithmetic exact match → {'PASS' if arithmetic_exact else 'FAIL'}")

P("")
P("[4/5] BM25 + Hybrid combiner + Citation validator:")
from nyaya.search.bm25_index import BM25Corpus
from nyaya.search.hybrid import combine_scores, validate_citations, HybridCandidate

class FakeS:
    def __init__(self, sid, title, bare_text, keywords=None, plain=None):
        self.id = sid; self.title = title; self.bare_text = bare_text
        self.keywords = keywords or []; self.plain_language = plain
        self.act = None
        self.section_number = str(sid)
        self.act_short_title = "SmokeCorpus"; self.act_year = 2024
        self.chapter = None

corpus = [
    FakeS(1, "Murder Punishment", "Whoever commits murder shall be punished with death or imprisonment for life.", ["murder","death","punishment","life"]),
    FakeS(2, "Culpable Homicide Not Amounting to Murder", "Culpable homicide not amounting to murder carries up to ten years imprisonment plus fine.", ["culpable","homicide","imprisonment"]),
    FakeS(3, "Theft Definition", "Dishonest taking of movable property out of possession without consent is theft.", ["theft","property","dishonest"]),
    FakeS(4, "Husband Cruelty 498A", "Cruelty by husband or his relatives includes dowry harassment and conduct likely to cause suicide.", ["cruelty","dowry","498a","suicide"]),
    FakeS(5, "Rape 376 Punishment", "Rape is punished with minimum ten years to life imprisonment and fine.", ["rape","imprisonment","376"]),
    FakeS(6, "Dowry Death 304B", "Where a woman dies within seven years of marriage after dowry harassment it is deemed dowry death.", ["dowry","death","304b","harassment"]),
    FakeS(7, "PMLA Section 3", "Any direct or indirect involvement in concealment or use of proceeds of crime is money-laundering.", ["pmla","money","laundering","proceeds","crime"]),
    FakeS(8, "BNS Murder 108", "Whoever commits murder shall be punished with death or imprisonment for life and fine.", ["bns","murder","death","life"]),
    FakeS(9, "SCST Atrocities 3", "Atrocities against SC/ST by non-SC/ST include tonsuring, garlanding chappals, gang rape.", ["scst","atrocity","poa","gang rape"]),
    FakeS(10, "IT Act 66", "Section 66 IT Act punishes dishonest and fraudulent computer misuse with 3 years or ₹5 lakh.", ["it act","66","hacking","dishonest"]),
]

bm25 = BM25Corpus.build(corpus)
bhits = bm25.query("murder death punishment", top_k=5)
dhits = [(1, 0.92), (8, 0.88), (5, 0.30), (2, 0.25), (3, 0.08)]  # BNS 108 (murder) highly dense-similar
combined = combine_scores(bhits, dhits)
# attach sec objects and helper attributes
for c in combined.values():
    obj = next((x for x in corpus if x.id == c.section_id), None)
    c.section_obj = obj
    if obj:
        c.title = obj.title
        c.bare_text = obj.bare_text

ordered = sorted(combined.values(), key=lambda c: c.combined_score, reverse=True)
validated = validate_citations("murder death punishment", ordered)
hybrid_ok = (
    ordered[0].section_id == 1  # Murder Punishment IPC ranked 1st
    and ordered[1].section_id == 8  # BNS murder sec 108 ranked 2nd
    and any(ok for _, ok, _, _ in validated)
)
valid_rows = []
for c, ok, sim, snips in validated[:6]:
    valid_rows.append({"section_id": c.section_id, "title": c.title[:60], "combined": round(c.combined_score, 3),
                       "citation_validated": ok, "citation_similarity": round(sim, 3), "snips": snips[:1]})
REPORT["hybrid_smoke"] = {
    "query": "murder death punishment",
    "bm25_top": [[sid, round(sc,3)] for sid, sc in bhits[:6]],
    "combined_ranked": [[c.section_id, c.title[:50], round(c.combined_score, 3)] for c in ordered[:6]],
    "validated": valid_rows,
    "expectations": {
        "rank_1": {"expected_section_id": 1, "name": "Murder Punishment (IPC 302 equivalent)"},
        "rank_2": {"expected_section_id": 8, "name": "BNS Sec 108 Murder Punishment"},
        "at_least_1_validated": True,
    },
    "passes_expectations": hybrid_ok,
}

P(f"  BM25 top: {[[sid, round(sc,2)] for sid, sc in bhits[:5]]}")
P(f"  Combined top 6:")
for c in ordered[:6]:
    marker = "  ★" if c.section_id in (1, 8) else ""
    P(f"    #{ordered.index(c)+1}  id={c.section_id}  score={c.combined_score:.3f}  {c.title[:52]}{marker}")
P(f"  Rank 1 = Sec 1 (murder)? {'✓' if ordered[0].section_id==1 else '✗'}")
P(f"  Rank 2 = Sec 8 (BNS murder)? {'✓' if len(ordered)>=2 and ordered[1].section_id==8 else '✗'}")
P(f"  ≥ 1 citation-validated result? {'✓' if any(ok for _,ok,_,_ in validated) else '✗'}")
P(f"  Hybrid expectations → {'PASS' if hybrid_ok else 'FAIL'}")

P("")
P("[5/5] Overall gate:")
REPORT["elapsed_seconds"] = round(time.perf_counter() - float(P_start if 'P_start' in globals() else (time.perf_counter()-0.001)), 3)
pass_gate = all([all_import_ok, seed_ok, arithmetic_exact, hybrid_ok])
REPORT["pass_gate"] = pass_gate
REPORT["pass_gate_breakdown"] = {
    "all_modules_import": all_import_ok,
    "baseline_counts_and_schema": seed_ok,
    "metric_arithmetic_exact_match": arithmetic_exact,
    "hybrid_rankings_expected": hybrid_ok,
}
P(f"  all_modules_import    → {'PASS' if all_import_ok else 'FAIL'}")
P(f"  baseline_seed_counts  → {'PASS' if seed_ok else 'FAIL'}")
P(f"  metric_arithmetic     → {'PASS' if arithmetic_exact else 'FAIL'}")
P(f"  hybrid_rank_expect    → {'PASS' if hybrid_ok else 'FAIL'}")
P(f"  OVERALL GATE          → {'✅ PASS' if pass_gate else '⚠️ FAIL'}")

out_path = EVD / f"evidence_{stamp}.json"
out_path.write_text(json.dumps(REPORT, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
latest = EVD / "LATEST.json"
try: latest.unlink()
except FileNotFoundError: pass
latest.write_text(json.dumps(REPORT, indent=2, ensure_ascii=False, default=str), encoding="utf-8")

log_path = EVD / f"run_{stamp}.log.txt"
log_path.write_text("\n".join(log_lines) + f"\n\nEvidence JSON → {out_path}\n", encoding="utf-8")
P(f"\nEvidence JSON written: {out_path}")
sys.exit(0 if pass_gate else 1)
