"""add rules, rule_sections, notifications tables

Revision ID: 4_add_rules_notifications_tables
Revises: 3_update_query_logs_schema
Create Date: 2026-06-25 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4_add_rules_notifications_tables'
down_revision: Union[str, None] = '3_update_query_logs_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_title', sa.String(length=300), nullable=False),
    sa.Column('full_title', sa.String(length=500), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('CRIMINAL', 'CIVIL', 'FAMILY', 'PROPERTY', 'LABOUR', 'CONSTITUTIONAL', 'CORPORATE', 'CONSUMER', 'CYBER', 'ENVIRONMENTAL', 'TAX', 'IPR', 'NARCOTICS', 'OTHER', name='lawcategory', create_type=False), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('qdrant_id', sa.String(length=100), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qdrant_id')
    )
    op.create_index(op.f('ix_rules_short_title'), 'rules', ['short_title'], unique=False)
    op.create_table('rule_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_section', 'rule_sections', ['rule_id', 'section_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_title', sa.String(length=300), nullable=False),
    sa.Column('full_title', sa.String(length=500), nullable=False),
    sa.Column('issuing_authority', sa.String(length=200), nullable=False),
    sa.Column('notification_date', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Enum('CRIMINAL', 'CIVIL', 'FAMILY', 'PROPERTY', 'LABOUR', 'CONSTITUTIONAL', 'CORPORATE', 'CONSUMER', 'CYBER', 'ENVIRONMENTAL', 'TAX', 'IPR', 'NARCOTICS', 'OTHER', name='lawcategory', create_type=False), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('qdrant_id', sa.String(length=100), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qdrant_id')
    )
    op.create_index(op.f('ix_notifications_short_title'), 'notifications', ['short_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_short_title'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_rule_section', table_name='rule_sections')
    op.drop_table('rule_sections')
    op.drop_index(op.f('ix_rules_short_title'), table_name='rules')
    op.drop_table('rules')
    # ### end Alembic commands ###
