"""add missing sections columns and chapters table

Revision ID: 5_add_missing_sections_columns_and_chapters_table
Revises: 4_add_rules_notifications_tables
Create Date: 2026-06-26 05:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5_add_chapters_and_sections_cols'
down_revision: Union[str, None] = '4_add_rules_notifications_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.String(length=50), nullable=False),
    sa.Column('chapter_title', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.add_column('sections', sa.Column('chapter_id', sa.Integer(), nullable=True))
    op.add_column('sections', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('sections', sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('sections', sa.Column('related_section_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('sections', sa.Column('effective_date', sa.String(length=50), nullable=True))
    op.add_column('sections', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, server_onupdate=sa.text('now()')))
    op.create_foreign_key(None, 'sections', 'chapters', ['chapter_id'], ['id'])
    
    op.add_column('amendments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, server_onupdate=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_column('sections', 'effective_date')
    op.drop_column('sections', 'related_section_ids')
    op.drop_column('sections', 'keywords')
    op.drop_column('sections', 'sort_order')
    op.drop_column('sections', 'chapter_id')
    op.drop_table('chapters')
    # ### end Alembic commands ###
