"""initial_schema

Revision ID: 9d2cc7087ac4
Revises: 
Create Date: 2026-05-12 21:57:23.744862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2cc7087ac4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_title', sa.String(length=300), nullable=False),
    sa.Column('full_title', sa.String(length=500), nullable=False),
    sa.Column('act_number', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('act_type', sa.Enum('CENTRAL', 'STATE', 'CONSTITUTIONAL', 'REGULATION', name='acttype'), nullable=False),
    sa.Column('category', sa.Enum('CRIMINAL', 'CIVIL', 'FAMILY', 'PROPERTY', 'LABOUR', 'CONSTITUTIONAL', 'CORPORATE', 'CONSUMER', 'CYBER', 'ENVIRONMENTAL', 'TAX', 'IPR', 'NARCOTICS', 'OTHER', name='lawcategory'), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('replaces_act_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaces_act_id'], ['acts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acts_short_title'), 'acts', ['short_title'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('intent_detected', sa.String(length=100), nullable=True),
    sa.Column('sections_cited', sa.Text(), nullable=True),
    sa.Column('ai_provider_used', sa.String(length=50), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_logs_session_id'), 'query_logs', ['session_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supabase_id', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_lawyer', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('daily_query_count', sa.Integer(), nullable=False),
    sa.Column('daily_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('bare_text', sa.Text(), nullable=False),
    sa.Column('plain_language', sa.Text(), nullable=True),
    sa.Column('is_bailable', sa.Boolean(), nullable=True),
    sa.Column('is_cognizable', sa.Boolean(), nullable=True),
    sa.Column('is_compoundable', sa.Boolean(), nullable=True),
    sa.Column('punishment_summary', sa.String(length=500), nullable=True),
    sa.Column('min_punishment', sa.String(length=200), nullable=True),
    sa.Column('max_punishment', sa.String(length=200), nullable=True),
    sa.Column('fine_amount', sa.String(length=200), nullable=True),
    sa.Column('relevant_court', sa.String(length=200), nullable=True),
    sa.Column('limitation_period', sa.String(length=200), nullable=True),
    sa.Column('qdrant_id', sa.String(length=100), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_amended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qdrant_id')
    )
    op.create_index('ix_sections_act_number', 'sections', ['act_id', 'section_number'], unique=False)
    op.create_table('amendments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.String(length=50), nullable=True),
    sa.Column('old_text', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=False),
    sa.Column('amendment_act', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amendments')
    op.drop_index('ix_sections_act_number', table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_query_logs_session_id'), table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_acts_short_title'), table_name='acts')
    op.drop_table('acts')
    # ### end Alembic commands ###
