from __future__ import annotations

from typing import Any

K = lambda *ks: list(ks)

SECTIONS: list[dict[str, Any]] = [
    *[
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER II - GENERAL EXPLANATIONS",
            "part": None,
            "section_number": "34",
            "title": "Acts done by several persons in furtherance of common intention",
            "bare_text": "When a criminal act is done by several persons in furtherance of the common intention of all, each of such persons is liable for that act in the same manner as if it were done by him alone.",
            "plain_language": "When a group of people together plan and commit a crime, every person in the group is equally responsible for the entire crime, even if they individually performed only a part of it.",
            "keywords": K("common intention", "group liability", "joint liability", "concerted action"),
            "punishments": None,
            "bailable": None,
            "cognizable": None,
            "compoundable": None,
            "source_page": 23,
            "extra_data": {},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER III - OF PUNISHMENTS",
            "part": None,
            "section_number": "53",
            "title": "Punishments",
            "bare_text": "The punishments to which offenders are liable under the provisions of this Code are:—First, Death; Secondly, Imprisonment for life; Thirdly, Imprisonment, which is of two descriptions, namely:—(1) Rigorous, that is, with hard labour; (2) Simple; Fourthly, Forfeiture of property; Fifthly, Fine.",
            "plain_language": "The five kinds of punishment available under the IPC are: death, life imprisonment, rigorous or simple imprisonment (up to 14 years extendable to life), forfeiture of property, and fine. These may be combined.",
            "keywords": K("punishment", "death penalty", "life imprisonment", "rigorous imprisonment", "fine", "forfeiture"),
            "punishments": "Death, life imprisonment, rigorous imprisonment, simple imprisonment, forfeiture, fine.",
            "bailable": None,
            "cognizable": None,
            "compoundable": None,
            "source_page": 31,
            "extra_data": {},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER VI - OF OFFENCES AGAINST THE STATE",
            "part": None,
            "section_number": "121",
            "title": "Waging, or attempting to wage war, or abetting waging of war, against the Government of India",
            "bare_text": "Whoever wages war against the Government of India, or attempts to wage such war, or abets the waging of such war, shall be punished with death, or imprisonment for life, and shall also be liable to fine.",
            "plain_language": "Any person who wages war (or tries to, or helps others to) against the Indian State can be sentenced to death or life imprisonment plus fine. This is the highest offence against sovereignty.",
            "keywords": K("treason", "sedition", "war against state", "sovereignty"),
            "punishments": "Death or imprisonment for life + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "death_penalty": True,
            "life_imprisonment": True,
            "imprisonment_max_months": 0,
            "source_page": 52,
            "extra_data": {},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVI - OF OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Offences Affecting Life",
            "section_number": "300",
            "title": "Murder",
            "bare_text": "Except in the cases hereinafter excepted, culpable homicide is murder, if the act by which the death is caused is done with the intention of causing death, or if it is done with the intention of causing such bodily injury as the offender knows to be likely to cause the death of the person to whom the harm is caused, or if it is done with the intention of causing bodily injury to any person and the bodily injury intended to be inflicted is sufficient in the ordinary course of nature to cause death, or if the person committing the act knows that it is so imminently dangerous that it must, in all probability, cause death or such bodily injury as is likely to cause death, and commits such act without any excuse for incurring the risk of causing death or such injury as aforesaid.",
            "plain_language": "A killing is murder (not just culpable homicide) when: (1) the accused specifically intended death; or (2) they inflicted a deliberate injury that any reasonable person would know is likely to kill; or (3) the injury itself was, by nature, deadly; or (4) the act was extremely dangerous with no legitimate excuse. Exceptions (grave provocation, sudden fight, private defence exceeding bounds, consent, etc.) downgrade it to Culpable Homicide not Amounting to Murder.",
            "keywords": K("murder", "culpable homicide", "intention to kill", "mens rea", "actus reus", "death"),
            "punishments": "See Sec 302 IPC — death or life imprisonment + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "death_penalty": True,
            "life_imprisonment": True,
            "source_page": 246,
            "extra_data": {"exceptions_count": 5, "cross_reference": "IPC Sec 299 (Culpable Homicide)"},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVI - OF OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Offences Affecting Life",
            "section_number": "302",
            "title": "Punishment for murder",
            "bare_text": "Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine.",
            "plain_language": "A person convicted of murder under Sec 300 IPC faces either the death penalty (rarest of rare) or mandatory life imprisonment plus fine. Death is given only in the 'rarest of rare' cases after weighing aggravating and mitigating factors (Bachan Singh v. State of Punjab, 1980 SC).",
            "keywords": K("murder punishment", "death penalty", "life imprisonment", "rarest of rare", "sentencing"),
            "punishments": "Death or imprisonment for life + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "death_penalty": True,
            "life_imprisonment": True,
            "fine_max": None,
            "source_page": 250,
            "extra_data": {"landmark_cases": ["Bachan Singh v. Union of India", "Machhi Singh v. State of Punjab"]},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVI - OF OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Offences Affecting Life",
            "section_number": "304",
            "title": "Punishment for culpable homicide not amounting to murder",
            "bare_text": "Whoever commits culpable homicide not amounting to murder shall be punished with imprisonment for life, or imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine, if the act by which the death is caused is done with the intention of causing death, or of causing such bodily injury as is likely to cause death; or with imprisonment of either description for a term which may extend to ten years, or with fine, or with both, if the act is done with the knowledge that it is likely to cause death, but without any intention to cause death, or to cause such bodily injury as is likely to cause death.",
            "plain_language": "When a killing is culpable homicide but NOT murder (falls under 300 exceptions or lacks the mens rea of murder): Part I (intended death/injury) → up to life imprisonment or 10 years rigorous/simple + fine. Part II (knew of risk but no intent) → up to 10 years, fine, or both.",
            "keywords": K("culpable homicide", "304 part i", "304 part ii", "dowry death cross ref"),
            "punishments": "Part I: Life/10 years + fine; Part II: 10 years/fine/both",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "life_imprisonment": True,
            "imprisonment_max_months": 120,
            "source_page": 252,
            "extra_data": {"split": "Part I intent / Part II knowledge"},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVI - OF OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of the Causing of Miscarriage, of Injuries to Unborn Children, of the Exposure of Infants, and of the Concealment of Births",
            "section_number": "312",
            "title": "Causing miscarriage",
            "bare_text": "Whoever voluntarily causes a woman with child to miscarry, shall, if such miscarriage be not caused in good faith for the purpose of saving the life of the woman, be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both; and, if the woman be quick with child, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.",
            "plain_language": "A person who causes a pregnant woman to miscarry (unless in good faith to save her life) faces 3 years/fine/both. If she has reached 'quickening' (foetal movements felt), the penalty increases to 7 years + fine.",
            "keywords": K("abortion", "miscarriage", "pregnancy", "medical termination"),
            "punishments": "Upto 3 years or 7 years (quick with child) + fine",
            "bailable": True,
            "cognizable": False,
            "compoundable": False,
            "imprisonment_max_months": 84,
            "source_page": 272,
            "extra_data": {"cross_reference": "Medical Termination of Pregnancy Act, 1971 overrides in permitted cases"},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVI - OF OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Hurt",
            "section_number": "320",
            "title": "Grievous hurt",
            "bare_text": "The following kinds of hurt only are designated as 'grievous':—Emasculation. Permanent privation of the sight of either eye. Permanent privation of the hearing of either ear. Privation of any member or joint. Destruction or permanent impairing of the powers of any member or joint. Permanent disfiguration of the head or face. Fracture or dislocation of a bone or tooth. Any hurt which endangers life or which causes the sufferer to be during the space of twenty days in severe bodily pain, or unable to follow his ordinary pursuits.",
            "plain_language": "The IPC lists exactly 8 injuries that automatically qualify as 'grievous' (serious): emasculation, eye sight loss, ear hearing loss, loss of any limb/joint, permanent disability, facial disfigurement, fracture/dislocation, and any hurt that threatens life or leaves the person bedridden or in severe pain for 20 days. All 8 categories carry harsher punishment under Sec 325/326.",
            "keywords": K("grievous hurt", "fracture", "disfigurement", "20 days pain", "hearing loss", "eyesight loss", "emasculation"),
            "punishments": "Sec 322/325 IPC: upto 7 years + fine; Sec 326 (dangerous weapon): upto life",
            "bailable": True,
            "cognizable": True,
            "compoundable": True,
            "imprisonment_max_months": 84,
            "source_page": 290,
            "extra_data": {"kinds": 8},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVI - OF OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Kidnapping, Abduction, Slavery and Forced Labour",
            "section_number": "354",
            "title": "Assault or criminal force to woman with intent to outrage her modesty",
            "bare_text": "Whoever assaults or uses criminal force to any woman, intending to outrage or knowing it to be likely that he will thereby outrage her modesty, shall be punished with imprisonment of either description for a term which shall not be less than one year but which may extend to five years, and shall also be liable to fine.",
            "plain_language": "Any act of assault or force on a woman whose intent (or likely effect) is to violate her modesty. The Criminal Law Amendment Act 2013 introduced a mandatory minimum of 1 year and maximum 5 years plus fine. Stalking, disrobing, and acid attacks are now separate offences under 354A-D.",
            "keywords": K("outrage of modesty", "assault on woman", "354a stalking", "354d voyeurism", "criminal force woman"),
            "punishments": "Min 1 year / Max 5 years + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "imprisonment_min_months": 12,
            "imprisonment_max_months": 60,
            "source_page": 339,
            "extra_data": {"amended_by": "Criminal Law Amendment Act 2013 (Nirbhaya Act)"},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVI - OF OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Kidnapping, Abduction, Slavery and Forced Labour",
            "section_number": "363",
            "title": "Punishment for kidnapping",
            "bare_text": "Whoever kidnaps any person from India or from lawful guardianship, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.",
            "plain_language": "Kidnapping from lawful guardianship applies to minors (<18F / <16M) and insane persons — any act of taking/enticing away from a lawful guardian without consent, even without force. Kidnapping from India means taking a person out of India without their (or their guardian's) consent. Either form is punishable up to 7 years + fine.",
            "keywords": K("kidnapping", "abduction", "guardianship", "minor", "ransom cross ref"),
            "punishments": "Upto 7 years + fine",
            "bailable": True,
            "cognizable": True,
            "compoundable": False,
            "imprisonment_max_months": 84,
            "source_page": 352,
            "extra_data": {"kinds": ["Sec 359 kidnapping from India", "Sec 360 from lawful guardianship"]},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVI - OF OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Rape",
            "section_number": "375",
            "title": "Rape",
            "bare_text": "A man is said to commit 'rape' if he: (a) penetrates his penis, to any extent, into the vagina, mouth, urethra or anus of a woman or makes her to do so with him or any other person; or (b) inserts, to any extent, any object or a part of the body, not being the penis, into the vagina, the urethra or anus of a woman or makes her to do so with him or any other person; or (c) manipulates any part of the body of a woman so as to cause penetration into the vagina, urethra, anus or any part of body of such woman or makes her to do so with him or any other person; or (d) applies his mouth to the vagina, anus, urethra of a woman or makes her to do so with him or any other person, under the circumstances falling under any of the following seven descriptions:—(1) against her will; (2) without her consent; (3) with her consent, when her consent has been obtained by putting her or any person in whom she is interested, in fear of death or of hurt; (4) with her consent, when the man knows that he is not her husband and that her consent is given because she believes that he is another man to whom she is or believes herself to be lawfully married; (5) with her consent, when, at the time of giving such consent, by reason of unsoundness of mind or intoxication or the administration by him personally or through another of any stupefying or unwholesome substance, she is unable to understand the nature and consequences of that to which she gives consent; (6) with or without her consent, when she is under eighteen years of age; (7) when she is unable to communicate consent.",
            "plain_language": "Rape under 375 (post 2013 Amendment) includes not just traditional penile-vaginal penetration but 7 categories of penetrative acts — penile, object, manipulation, and oral — with 7 categories of lack of consent: against will, without consent, fear-induced consent, impersonation-of-husband consent, intoxicated/unsound-mind consent, under-18, and inability to communicate consent. Marital rape is NOT generally recognised (exception 2: intercourse by husband with wife ≥15 is not rape). Sec 376 carries punishment min 10 years / life / death (for gang rape, custodial rape, pregnant woman, under 16, etc.).",
            "keywords": K("rape", "sexual assault", "375", "consent", "nirbhaya act 2013", "penetration", "marital rape exception", "custodial rape"),
            "punishments": "Sec 376: min 10 years rigorous → life; Sec 376A/B/D: death/life for aggravated/custodial/gang; Sec 376AB/DB for <12 → mandatory death or 20 years to life",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "life_imprisonment": True,
            "death_penalty": True,
            "imprisonment_min_months": 120,
            "source_page": 378,
            "extra_data": {"amended_by": ["Criminal Law Amendment Act 2013", "Criminal Law Amendment Act 2018"], "exceptions": ["Exception 1 — medical/procedure in good faith", "Exception 2 — conjugal (≥15)"]},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVI - OF OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Rape",
            "section_number": "376",
            "title": "Punishment for rape",
            "bare_text": "(1) Whoever, except in the cases provided for by sub-section (2), commits rape shall be punished with imprisonment of either description for a term which shall not be less than ten years but which may be for life and shall also be liable to fine: ...",
            "plain_language": "Basic rape (non-aggravated): minimum 10 years rigorous, maximum life imprisonment, plus fine. Aggravated categories (376A/AB/B/C/D/DB) — gang rape, custodial, armed forces, public servant, during communal violence, pregnant, below 16/12, repeat offender — carry mandatory minimum 20 years, extendable to life, or death for <12.",
            "keywords": K("376 punishment", "gang rape 376d", "custodial rape", "minimum sentencing", "2013 amendment", "pooja singh guidelines"),
            "punishments": "Min 10 years → life + fine; aggravated = 20y/life/death",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "life_imprisonment": True,
            "imprisonment_min_months": 120,
            "source_page": 380,
            "extra_data": {"subsections": ["376A (death from rape)", "376AB (<12)", "376B (husband separated)", "376C (custodial)", "376D (gang rape)", "376DB (gang <12)", "376E (repeat)"]},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVI - OF OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Criminal Intimidation, Insult and Annoyance",
            "section_number": "498A",
            "title": "Husband or relative of husband of a woman subjecting her to cruelty",
            "bare_text": "Whoever, being the husband or the relative of the husband of a woman, subjects such woman to cruelty shall be punished with imprisonment for a term which may extend to three years and shall also be liable to fine. Explanation.—For the purpose of this section, 'cruelty' means—(a) any willful conduct which is of such a nature as is likely to drive the woman to commit suicide or to cause grave injury or danger to life, limb or health (whether mental or physical) of the woman; or (b) harassment of the woman where such harassment is with a view to coercing her or any person related to her to meet any unlawful demand for any property or valuable security or is on account of failure by her or any person related to her to meet such demand.",
            "plain_language": "Sec 498A IPC criminalises cruelty by a husband or his relatives toward a married woman. Cruelty covers (a) conduct likely to cause suicide or grave physical/mental harm, and (b) dowry-related harassment to extract property or valuables from the woman or her family. Punishment is up to 3 years + fine. This is a cognizable and non-bailable offence. Since 2014 SC guidelines in Arnesh Kumar v State of Bihar require police to issue a 'notice of appearance' prior to arrest to prevent misuse.",
            "keywords": K("498a", "cruelty", "dowry harassment", "suicide abetment cross", "matrimonial cruelty", "arnesh kumar guidelines", "mental cruelty"),
            "punishments": "Upto 3 years + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": True,
            "imprisonment_max_months": 36,
            "source_page": 480,
            "extra_data": {"landmark_cases": ["Arnesh Kumar v. State of Bihar (2014 SC)", "Sushil Kumar Sharma v. Union of India (2005)"]},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVI - OF OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Unnatural Offences",
            "section_number": "377",
            "title": "Unnatural offences",
            "bare_text": "Whoever voluntarily has carnal intercourse against the order of nature with any man, woman or animal, shall be punished with imprisonment for life, or with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine.",
            "plain_language": "The section historically criminalised consensual same-sex relations and non-procreative sex. In Navtej Singh Johar v. Union of India (2018 SC 5-judge bench), the SC decriminalised consensual adult intercourse (penetrative or otherwise) between adults in private, including same-sex intercourse. The section remains in force only for non-consensual acts, acts with minors, and bestiality.",
            "keywords": K("377", "lgbtq", "sodomy", "navtej singh johar 2018", "decriminalisation", "bestiality"),
            "punishments": "Life / upto 10 years + fine (only non-consensual/minor/animal retained)",
            "bailable": True,
            "cognizable": False,
            "compoundable": False,
            "life_imprisonment": True,
            "imprisonment_max_months": 120,
            "source_page": 395,
            "extra_data": {"decriminalised_consensual": "2018-09-06", "landmark": "Navtej Singh Johar v. UOI (2018)"},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVII - OF OFFENCES AGAINST PROPERTY",
            "part": "Of Theft",
            "section_number": "378",
            "title": "Theft",
            "bare_text": "Whoever, intending to take dishonestly any movable property out of the possession of any person without that person's consent, moves that property in order to such taking, is said to commit theft.",
            "plain_language": "Theft requires 5 ingredients: (1) movable property, (2) in the possession of another (not necessarily ownership), (3) dishonest intention to permanently deprive, (4) without consent (express or implied), and (5) physical movement of the property as part of the taking. Dishonest intention is the most critical element; if the taker genuinely believed in legal right, it is not theft.",
            "keywords": K("theft", "dishonest intention", "movable property", "possession", "without consent", "asportation"),
            "punishments": "Sec 379: upto 3 years or fine or both",
            "bailable": True,
            "cognizable": False,
            "compoundable": True,
            "imprisonment_max_months": 36,
            "source_page": 400,
            "extra_data": {"ingredients": 5, "cross_refs": ["Sec 379 punishment", "Sec 380 in dwelling", "Sec 381 clerk", "Sec 382 preparation"]},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVII - OF OFFENCES AGAINST PROPERTY",
            "part": "Of Extortion",
            "section_number": "383",
            "title": "Extortion",
            "bare_text": "Whoever intentionally puts any person in fear of any injury to that person, or to any other, and thereby dishonestly induces the person so put in fear to deliver to any person any property or valuable security, or anything signed or sealed which may be converted into a valuable security, commits 'extortion'.",
            "plain_language": "Extortion = fear of injury (to self or another person) + dishonest inducement + delivery of property/valuable security/signed document. The key difference from theft is the element of consent — the victim 'consents' to give property because of fear, and that consent is vitiated. Robbery is theft or extortion when accompanied by immediate violence or fear thereof (Sec 390).",
            "keywords": K("extortion", "fear of injury", "delivery of property", "vitiated consent", "robbery cross ref"),
            "punishments": "Sec 384: 3 years/fine/both; aggravated forms upto 10 years",
            "bailable": True,
            "cognizable": True,
            "compoundable": True,
            "imprisonment_max_months": 36,
            "source_page": 409,
            "extra_data": {"cross_refs": ["Sec 384 punishment", "Sec 390 robbery = theft/extortion + violence"]},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVII - OF OFFENCES AGAINST PROPERTY",
            "part": "Of Robbery and Dacoity",
            "section_number": "390",
            "title": "Robbery",
            "bare_text": "In all robbery there is either theft or extortion. When theft is robbery: Theft is 'robbery' if, in order to the committing of the theft, or in committing the theft, or in carrying away or attempting to carry away the property obtained by theft, the offender, for that end, voluntarily causes or attempts to cause to any person death or hurt or wrongful restraint, or fear of instant death or of instant hurt, or of instant wrongful restraint. When extortion is robbery: Extortion is 'robbery' if the offender, at the time of committing the extortion, is in the presence of the person put in fear, and commits the extortion by putting that person in fear of instant death, of instant hurt, or of instant wrongful restraint to that person or to some other person, and, by so putting in fear, induces the person so put in fear then and there to deliver up the thing extorted.",
            "plain_language": "Robbery = Theft or Extortion PLUS an aggravating overlay of actual or threatened immediate violence (death, hurt, wrongful restraint) to accomplish the taking or escape. Five or more persons conjointly committing or attempting a robbery is Dacoity (Sec 391), which is punishable with minimum 10 years to life + fine (Sec 395) and with death if murder is committed in the course of dacoity (Sec 396).",
            "keywords": K("robbery", "390", "dacoity 391", "396 dacoity with murder", "violence in theft", "instant violence"),
            "punishments": "Sec 392: upto 10 years rigorous + fine (14 years if highway); Sec 395 dacoity: min 10 years → life; Sec 396: death or life for dacoity + murder",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "life_imprisonment": True,
            "death_penalty": True,
            "imprisonment_max_months": 240,
            "source_page": 416,
            "extra_data": {"dacoity_threshold": 5, "cross_refs": ["391 dacoity", "395", "396 murder"]},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVII - OF OFFENCES AGAINST PROPERTY",
            "part": "Of Criminal Breach of Trust",
            "section_number": "405",
            "title": "Criminal breach of trust",
            "bare_text": "Whoever, being in any manner entrusted with property, or with any dominion over property, either solely or jointly with any other person, dishonestly misappropriates or converts to his own use that property, or dishonestly uses or disposes of that property in violation of any direction of law prescribing the mode in which such trust is to be discharged, or of any legal contract, express or implied, which he has made touching the discharge of such trust, or willfully suffers any other person so to do, commits 'criminal breach of trust'.",
            "plain_language": "CBT requires: (1) entrustment of property/dominion over property, (2) dishonest misappropriation/conversion/use/disposal, OR (3) dishonest violation of the lawful terms of the trust, or knowingly allowing another to do so. Key difference from theft is that the accused was already in lawful possession of the property — the wrong is the breach of trust, not the taking. Variants are carrier (407), clerk/servant (408), public servant/banker/merchant (409 — up to life).",
            "keywords": K("criminal breach of trust", "405", "entrustment", "dishonest conversion", "fiduciary duty"),
            "punishments": "Sec 406: upto 3 years/fine/both; Sec 409 (public servant/banker): upto life",
            "bailable": True,
            "cognizable": False,
            "compoundable": True,
            "life_imprisonment": True,
            "imprisonment_max_months": 36,
            "source_page": 435,
            "extra_data": {"cross_refs": ["406 general", "407 carrier", "408 clerk servant", "409 banker public servant"]},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVII - OF OFFENCES AGAINST PROPERTY",
            "part": "Of the Receiving of Stolen Property",
            "section_number": "411",
            "title": "Dishonestly receiving stolen property",
            "bare_text": "Whoever dishonestly receives or retains any stolen property, knowing or having reason to believe the same to be stolen property, shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.",
            "plain_language": "Sec 411 punishes those who deal in stolen goods with knowledge or reasonable belief that they are stolen. This is the general offence; 412 punishes receiving property acquired by dacoity (10 years), 413 deals with habitual receivers (life), 414 assists in concealment (upto 3 years). Property is 'stolen property' if obtained by theft, extortion, robbery, dacoity, criminal misappropriation, or CBT.",
            "keywords": K("receiving stolen property", "411", "stolen goods", "mens rea knowledge", "dishonest retention"),
            "punishments": "Upto 3 years / fine / both",
            "bailable": True,
            "cognizable": False,
            "compoundable": True,
            "imprisonment_max_months": 36,
            "source_page": 445,
            "extra_data": {"definition_of_stolen": "Sec 410 theft extortion robbery dacoity misappropriation CBT"},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVII - OF OFFENCES AGAINST PROPERTY",
            "part": "Of Cheating",
            "section_number": "415",
            "title": "Cheating",
            "bare_text": "Whoever, by deceiving any person, fraudulently or dishonestly induces the person so deceived to deliver any property to any person, or to consent that any person shall retain any property, or intentionally induces the person so deceived to do or omit to do anything which he would not do or omit if he were not so deceived, and which act or omission causes or is likely to cause damage or harm to that person in body, mind, reputation or property, is said to 'cheat'.",
            "plain_language": "Cheating = Deception (making a false representation of a fact) + inducement that is either fraudulent/dishonest to get property, OR that causes the person to do/omit something resulting in damage/harm to body, mind, reputation, or property. Sec 416 adds 'cheating by personation' (impersonation). Sec 420 is the aggravated form — cheating and thereby dishonestly inducing delivery of property or alteration/destruction of a valuable security — which is more severely punished and non-bailable.",
            "keywords": K("cheating", "415", "420 aggravated", "deception", "dishonest inducement", "personation 416", "valuable security"),
            "punishments": "Sec 417: upto 1 year / fine / both; Sec 419: upto 3 years; Sec 420: upto 7 years + fine",
            "bailable": True,
            "cognizable": False,
            "compoundable": True,
            "imprisonment_max_months": 12,
            "source_page": 455,
            "extra_data": {"cross_refs": ["417 415 punishment", "419 416 punishment", "420 aggravated property damage"]},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVII - OF OFFENCES AGAINST PROPERTY",
            "part": "Of Cheating",
            "section_number": "420",
            "title": "Cheating and dishonestly inducing delivery of property",
            "bare_text": "Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, or anything which is signed or sealed, and which is capable of being converted into a valuable security, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.",
            "plain_language": "420 = cheating under 415 + dishonest inducement to (a) deliver any property, OR (b) make, alter, destroy a valuable security. This is the 'classic 420' charge used in most financial frauds, loan frauds, investment scams, cheque dishonour cases (combined with NI Act 138), marriage frauds, fake document scams. Punishment: up to 7 years + fine, cognizable, non-bailable.",
            "keywords": K("420 ipc", "fraud", "dishonest delivery", "valuable security", "cheating 420", "scam", "financial fraud"),
            "punishments": "Upto 7 years + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "imprisonment_max_months": 84,
            "source_page": 460,
            "extra_data": {"used_with": ["NI Act 138 (cheque bounce)", "PMLA money laundering"]},
        },
        {
            "act_short_title": "Indian Penal Code, 1860",
            "chapter": "CHAPTER XVI - OF OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Offences Affecting Life",
            "section_number": "304B",
            "title": "Dowry death",
            "bare_text": "(1) Where the death of a woman is caused by any burns or bodily injury or occurs otherwise than under normal circumstances within seven years of her marriage and it is shown that soon before her death she was subjected to cruelty or harassment by her husband or any relative of her husband for, or in connection with, any demand for dowry, such death shall be called 'dowry death', and such husband or relative shall be deemed to have caused her death. (2) Whoever commits dowry death shall be punished with imprisonment for a term which shall not be less than seven years but which may extend to imprisonment for life.",
            "plain_language": "Sec 304B IPC is a deeming provision that targets the high incidence of 'bride burning' and dowry harassment killings. Ingredients: (1) death of a woman within 7 years of marriage, (2) caused by burns/abnormal bodily injury/not natural, (3) soon before death she was subjected to cruelty/harassment by husband or his relatives, (4) the cruelty was FOR or IN CONNECTION WITH ANY DEMAND FOR DOWRY. If these are met, the husband/relative is DEEMED to have caused her death — the burden of proof shifts heavily. Punishment: minimum 7 years, maximum life imprisonment. It is cognizable, non-bailable, non-compoundable, triable by Sessions.",
            "keywords": K("dowry death", "304b", "bride burning", "seven years rule", "deemed causation", "dowry demand", "presumption 113b evidence act"),
            "punishments": "Min 7 years → life imprisonment",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "life_imprisonment": True,
            "imprisonment_min_months": 84,
            "source_page": 260,
            "extra_data": {"evidence_presumption": "Sec 113B Indian Evidence Act", "cross_ref": ["Sec 498A cruelty", "Dowry Prohibition Act 1961"]},
        },
    ],
    *[
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 3 - GENERAL EXPLANATIONS",
            "part": None,
            "section_number": "14",
            "title": "When a criminal act is done by several persons, each is liable in the same manner",
            "bare_text": "When a criminal act is done by several persons, in furtherance of the common intention of all, each of such persons is liable for that act in the same manner as if it were done by him alone.",
            "plain_language": "Equivalent to IPC Sec 34: group liability where all who acted together pursuant to a shared criminal intention are fully liable for the entire offence.",
            "keywords": K("common intention", "group liability", "concert"),
            "bailable": None,
            "cognizable": None,
            "compoundable": None,
            "source_page": 18,
            "extra_data": {"maps_ipc_section": "34"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 5 - OF PUNISHMENTS",
            "part": None,
            "section_number": "27",
            "title": "Punishments",
            "bare_text": "The punishments to which offenders are liable under the provisions of this Sanhita are:—(a) Death; (b) Imprisonment for life; (c) Imprisonment which is of two descriptions, namely:—(i) Rigorous, that is with hard labour; (ii) Simple; (d) Community Service; (e) Forfeiture of property; (f) Fine.",
            "plain_language": "BNS retains IPC's death/life/rigorous/simple/forfeiture/fine but ADDs a new 'Community Service' punishment as an alternative for minor offences (eg Sec 67 small thefts, Sec 188 public servant obstruction, Sec 354 molestation as reduced). This is a key reform: community service of up to 100 hours for petty offences reduces jail crowding.",
            "keywords": K("bns punishments", "community service", "death", "life imprisonment", "reformative justice"),
            "punishments": "Death, Life, Rigorous, Simple, Community Service, Forfeiture, Fine",
            "source_page": 33,
            "extra_data": {"maps_ipc_section": "53", "new_punishment": "Community Service"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 6 - OF OFFENCES AGAINST THE STATE",
            "part": None,
            "section_number": "131",
            "title": "Waging war or attempt or abetment",
            "bare_text": "Whoever wages war against the Government of India, or attempts to wage such war, or abets the waging of such war, shall be punished with death, or imprisonment for life, and shall also be liable to fine. Explanation: A person who wages war against the Government of India shall include a person who participates, either as a member of a group of persons or otherwise, in the commission of an offence of waging war.",
            "plain_language": "Equivalent to IPC Sec 121 — war against the state: death or life + fine. The BNS adds an explanation that mere 'participation' — even as a member of a group and not necessarily as a leader or combatant — suffices for the offence.",
            "keywords": K("treason", "war against state", "waging war bns"),
            "punishments": "Death or life + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "death_penalty": True,
            "life_imprisonment": True,
            "source_page": 67,
            "extra_data": {"maps_ipc_section": "121"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 12 - OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Offences Affecting Life",
            "section_number": "107",
            "title": "Murder",
            "bare_text": "Except in the cases hereinafter excepted, culpable homicide is murder, if the act by which the death is caused is done with the intention of causing death, or if it is done with the intention of causing such bodily injury as the offender knows to be likely to cause the death of the person to whom the harm is caused, or if it is done with the intention of causing bodily injury to any person and the bodily injury intended to be inflicted is sufficient in the ordinary course of nature to cause death, or if the person committing the act knows that it is so imminently dangerous that it must, in all probability, cause death or such bodily injury as is likely to cause death, and commits such act without any excuse for incurring the risk of causing death or such injury as aforesaid.",
            "plain_language": "The definition of murder in BNS Sec 107 is nearly identical to IPC Sec 300 (4 limbs + 5 exceptions). The exceptions for grave provocation, sudden fight, exceeding private defence, etc. remain. Punishment is under Sec 108 BNS.",
            "keywords": K("murder", "culpable homicide", "intention", "mens rea", "rarest of rare"),
            "punishments": "Sec 108 — death or life + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "death_penalty": True,
            "life_imprisonment": True,
            "source_page": 130,
            "extra_data": {"maps_ipc_section": "300"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 12 - OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Offences Affecting Life",
            "section_number": "108",
            "title": "Punishment for murder",
            "bare_text": "Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine.",
            "plain_language": "Punishment for murder under the BNS is identical to IPC 302: death (rarest of rare) or mandatory life imprisonment, plus fine. The Bachan Singh and Machhi Singh sentencing frameworks remain operative as constitutional precedent.",
            "keywords": K("bns 108", "murder punishment", "rarest of rare", "bachan singh"),
            "punishments": "Death or imprisonment for life + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "death_penalty": True,
            "life_imprisonment": True,
            "source_page": 131,
            "extra_data": {"maps_ipc_section": "302"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 12 - OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Offences Affecting Life",
            "section_number": "109",
            "title": "Punishment for culpable homicide not amounting to murder",
            "bare_text": "Whoever commits culpable homicide not amounting to murder, shall be punished with imprisonment for life, or with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine, if the act by which the death is caused is done with the intention of causing death, or of causing such bodily injury as is likely to cause death; or with imprisonment of either description for a term which may extend to ten years, or with fine, or with both, if the act is done with the knowledge that it is likely to cause death, but without any intention to cause death, or to cause such bodily injury as is likely to cause death.",
            "plain_language": "BNS mirrors IPC Sec 304 split — Part I (intention): life / up to 10 years + fine. Part II (knowledge, no intent): up to 10 years, fine, or both. No change from IPC.",
            "keywords": K("culpable homicide", "bns 109", "part i intent", "part ii knowledge"),
            "punishments": "Part I: Life or 10 years + fine; Part II: 10 years/fine/both",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "life_imprisonment": True,
            "imprisonment_max_months": 120,
            "source_page": 132,
            "extra_data": {"maps_ipc_section": "304"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 12 - OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Offences Affecting Life",
            "section_number": "112",
            "title": "Abetment of suicide of child or insane person",
            "bare_text": "If any person under eighteen years of age, any insane person, any delirious person, any idiot, or any person in a state of intoxication, commits suicide, whoever abets the commission of such suicide, shall be punished with death or imprisonment for life, or imprisonment for a term not exceeding ten years, and shall also be liable to fine.",
            "plain_language": "Abetting suicide of a minor/insane/intoxicated person remains punishable up to death OR life OR 10 years + fine (same as IPC 305). The 2023 BNS adds Sec 113 (abetment of suicide by married woman within 7 years by cruelty/husband/relatives — min 5 years / max 10 years) as a new standalone section for matrimonial abetment cases.",
            "keywords": K("abetment suicide", "minor suicide", "insane suicide", "bns 112 113", "suicide note"),
            "punishments": "Death or life or upto 10 years + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "death_penalty": True,
            "life_imprisonment": True,
            "imprisonment_max_months": 120,
            "source_page": 137,
            "extra_data": {"maps_ipc_section": "305", "new_in_bns": ["Sec 113 abetment of married woman suicide"]},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 12 - OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Grievous Hurt",
            "section_number": "117",
            "title": "Grievous hurt",
            "bare_text": "The following kinds of hurt only are designated as 'grievous':—(a) emasculation; (b) permanent privation of the sight of either eye; (c) permanent privation of the hearing of either ear; (d) privation of any member or joint; (e) destruction or permanent impairing of the powers of any member or joint; (f) permanent disfiguration of the head or face; (g) fracture or dislocation of a bone or tooth; (h) any hurt which endangers life or which causes the sufferer to be during the space of twenty days in severe bodily pain, or unable to follow his ordinary pursuits.",
            "plain_language": "The 8 categories of grievous hurt are identical to IPC Sec 320. No change.",
            "keywords": K("grievous hurt bns", "fracture", "disfigurement", "20 days"),
            "punishments": "Sec 120 BNS voluntary grievous: upto 7 years + fine",
            "bailable": True,
            "cognizable": True,
            "compoundable": True,
            "imprisonment_max_months": 84,
            "source_page": 150,
            "extra_data": {"maps_ipc_section": "320"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 12 - OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Sexual Offences",
            "section_number": "63",
            "title": "Sexual intercourse by employing deceitful means etc.",
            "bare_text": "Whoever, by deceitful means or by making a promise to marry to a woman without any intention of fulfilling that promise, or by other false promise, induces her to have sexual intercourse with him, shall be punished with imprisonment of either description for a term which may extend to ten years, and with fine. Explanation: For the purposes of this section, the expression 'deceitful means' shall include the false promise of employment, false promise of promotion, or giving any false information or concealing the identity of the accused to have sexual intercourse.",
            "plain_language": "BNS Sec 63 is a BRAND NEW offence introduced by the 2023 Sanhita — the 'rape by deceit' / 'false promise to marry' provision. IPC 375's consent categories did not explicitly cover false promise of marriage, which led to inconsistent case law. BNS now criminalises (1) making a marriage promise with no intent to honour, (2) false employment/promotion promises, (3) identity concealment, (4) any other deceit, to obtain sexual consent. Punishment is up to 10 years + fine.",
            "keywords": K("bns 63", "false promise to marry", "rape by deceit", "new offence bns 2023", "consent by fraud", "identity concealment"),
            "punishments": "Upto 10 years + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "imprisonment_max_months": 120,
            "source_page": 78,
            "extra_data": {"maps_ipc_section": "NEW", "enforcement": "2024-07-01"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 12 - OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Sexual Offences",
            "section_number": "75",
            "title": "Assault or use of criminal force to woman with intent to outrage her modesty",
            "bare_text": "Whoever assaults or uses criminal force to any woman, intending to outrage or knowing it to be likely that he will thereby outrage her modesty, shall be punished with imprisonment of either description for a term which shall not be less than one year but which may extend to five years, and shall also be liable to fine.",
            "plain_language": "Equivalent to IPC Sec 354. Outraging a woman's modesty by assault or criminal force: min 1 year / max 5 years + fine. The separate 354A/354C/354D of IPC (sexual harassment, disrobing, voyeurism, stalking) are restructured into BNS Secs 74, 76, 77, 78.",
            "keywords": K("outrage modesty bns", "sexual harassment", "criminal force woman", "bns 74 75 76 77 78"),
            "punishments": "Min 1 year / Max 5 years + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "imprisonment_min_months": 12,
            "imprisonment_max_months": 60,
            "source_page": 112,
            "extra_data": {"maps_ipc_section": "354"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 12 - OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Kidnapping, Abduction and Slavery",
            "section_number": "84",
            "title": "Punishment for kidnapping",
            "bare_text": "Whoever kidnaps any person from Bharat or from lawful guardianship, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.",
            "plain_language": "Equivalent to IPC Sec 363. Upto 7 years + fine for kidnapping from India (renamed 'Bharat' in the Sanhita) or from lawful guardianship.",
            "keywords": K("kidnapping", "bns 84", "guardianship", "bharat"),
            "punishments": "Upto 7 years + fine",
            "bailable": True,
            "cognizable": True,
            "compoundable": False,
            "imprisonment_max_months": 84,
            "source_page": 123,
            "extra_data": {"maps_ipc_section": "363"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 12 - OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Sexual Offences",
            "section_number": "65",
            "title": "Rape",
            "bare_text": "A man is said to commit 'rape' if he: (a) penetrates his penis, to any extent, into the vagina, mouth, urethra or anus of a woman or makes her to do so with him or any other person; or (b) inserts, to any extent, any object or a part of the body, not being the penis, into the vagina, the urethra or anus of a woman or makes her to do so with him or any other person; or (c) manipulates any part of the body of a woman so as to cause penetration into the vagina, urethra, anus or any part of body of such woman or makes her to do so with him or any other person; or (d) applies his mouth to the vagina, anus, urethra of a woman or makes her to do so with him or any other person, under the circumstances falling under any of the following seven descriptions:—(1) against her will; (2) without her consent; (3) with her consent, when her consent has been obtained by putting her or any person in whom she is interested in fear of death or of hurt; (4) with her consent, when the man knows that he is not her husband and that her consent is given because she believes that he is another man to whom she is lawfully married; (5) with her consent, when, at the time of giving such consent, by reason of unsoundness of mind or intoxication or the administration by him personally or through another of any stupefying or unwholesome substance, she is unable to understand the nature and consequences of that to which she gives consent; (6) with or without her consent, when she is under eighteen years of age; (7) when she is unable to communicate consent.",
            "plain_language": "BNS Sec 65 = IPC Sec 375 (identical 4 limbs, 7 consent categories). BNS retains Exception 2 (marital rape exception, though the age of the wife was raised to 18 in 2023 BNS — previously 15 in IPC). Punishment under Sec 66 is min 10 years to life, with aggravated Sec 67 AB/DB (<12 = death/life). BNS also added Sec 68 'Rape by organised crime' with mandatory life or death penalty.",
            "keywords": K("rape", "bns 65", "66 punishment", "consent", "68 rape organised crime death", "marital age raised 18"),
            "punishments": "Sec 66: min 10 years → life + fine; aggravated/death under Sec 67 A/B/AB/DB; Sec 68: life or death",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "life_imprisonment": True,
            "death_penalty": True,
            "imprisonment_min_months": 120,
            "source_page": 85,
            "extra_data": {"maps_ipc_section": "375", "raised_wife_exception_age": "15→18"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 12 - OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Cruelty Leading to Suicide or Dowry Death",
            "section_number": "124",
            "title": "Husband or relative of husband subjecting woman to cruelty",
            "bare_text": "Whoever, being the husband or the relative of the husband of a woman, subjects such woman to cruelty shall be punished with imprisonment for a term which may extend to three years and shall also be liable to fine. Explanation.—For the purposes of this section,—(a) 'cruelty' means—(i) any willful conduct which is of such a nature as is likely to drive the woman to commit suicide or to cause grave injury or danger to life, limb or health (whether mental or physical) of the woman; or (ii) harassment of the woman where such harassment is with a view to coercing her or any person related to her to meet any unlawful demand for any property or valuable security or is on account of failure by her or any person related to her to meet such demand.",
            "plain_language": "BNS Sec 124 mirrors IPC Sec 498A. Up to 3 years + fine for cruelty by husband or his in-laws. Arnesh Kumar guidelines still apply to prevent arbitrary arrests.",
            "keywords": K("498a equivalent bns", "cruelty", "dowry demand", "124 bns", "suicide risk"),
            "punishments": "Upto 3 years + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": True,
            "imprisonment_max_months": 36,
            "source_page": 168,
            "extra_data": {"maps_ipc_section": "498A"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 12 - OFFENCES AFFECTING THE HUMAN BODY",
            "part": "Of Cruelty Leading to Suicide or Dowry Death",
            "section_number": "126",
            "title": "Dowry death",
            "bare_text": "(1) Where the death of a woman is caused by any burns or bodily injury or occurs otherwise than under normal circumstances within seven years of her marriage and it is shown that soon before her death she was subjected to cruelty or harassment by her husband or any relative of her husband for, or in connection with, any demand for dowry, such death shall be called 'dowry death', and such husband or relative shall be deemed to have caused her death. (2) Whoever commits dowry death shall be punished with imprisonment for a term which shall not be less than seven years but which may extend to imprisonment for life.",
            "plain_language": "Identical to IPC Sec 304B — 7 year rule, deemed causation, demand for dowry. Min 7 years → life. Presumption 113B Evidence Act (now Bharatiya Sakshya Sec 113B) still applies.",
            "keywords": K("dowry death", "bns 126", "seven years", "deemed causation"),
            "punishments": "Min 7 years → life",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "life_imprisonment": True,
            "imprisonment_min_months": 84,
            "source_page": 170,
            "extra_data": {"maps_ipc_section": "304B"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 13 - OFFENCES AGAINST PROPERTY",
            "part": "Of Theft",
            "section_number": "306",
            "title": "Theft",
            "bare_text": "Whoever, intending to take dishonestly any movable property out of the possession of any person without that person's consent, moves that property in order to such taking, is said to commit theft.",
            "plain_language": "Identical to IPC Sec 378. 5 ingredients: movable property, possession of another, dishonest intention, without consent, movement. Punishment under Sec 307 — but BNS notably ADDS a community service option for small thefts (Sec 308 punishment for theft upto Rs 5,000 is max 1 year or fine or community service).",
            "keywords": K("theft bns", "306", "community service small thefts"),
            "punishments": "Sec 307: upto 3 years/fine; Sec 308 (<5k): 1 year/fine/community service",
            "bailable": True,
            "cognizable": False,
            "compoundable": True,
            "imprisonment_max_months": 36,
            "source_page": 300,
            "extra_data": {"maps_ipc_section": "378", "new_thresholds": "Sec 308 small theft < ₹5k community service"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 13 - OFFENCES AGAINST PROPERTY",
            "part": "Of Extortion, Robbery and Dacoity",
            "section_number": "323",
            "title": "Robbery",
            "bare_text": "There is robbery in all cases either of theft or extortion. When theft is robbery. Theft is 'robbery' if, in order to the committing of the theft, or in committing the theft, or in carrying away or attempting to carry away the property obtained by theft, the offender, for that end, voluntarily causes or attempts to cause to any person death or hurt or wrongful restraint, or fear of instant death or of instant hurt, or of instant wrongful restraint. When extortion is robbery. Extortion is 'robbery' if the offender, at the time of committing the extortion, is in the presence of the person put in fear, and commits the extortion by putting that person in fear of instant death, of instant hurt, or of instant wrongful restraint to that person or to some other person, and, by so putting in fear, induces the person so put in fear then and there to deliver up the thing extorted.",
            "plain_language": "Equivalent to IPC 390. Robbery = theft/extortion PLUS immediate violence or threat. 5+ persons conjointly committing is Dacoity (Sec 324; Sec 328 punishment = min 10 years → life; Sec 329 dacoity with murder = death or life).",
            "keywords": K("robbery bns", "323", "dacoity 324", "329 death"),
            "punishments": "Sec 325 punishment: upto 10 years rigorous + fine; 328 dacoity: 10 years→life; 329 death or life",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "life_imprisonment": True,
            "death_penalty": True,
            "imprisonment_max_months": 240,
            "source_page": 333,
            "extra_data": {"maps_ipc_section": "390"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 13 - OFFENCES AGAINST PROPERTY",
            "part": "Of Cheating",
            "section_number": "345",
            "title": "Cheating and dishonestly inducing delivery of property",
            "bare_text": "Whoever cheats and thereby dishonestly induces the person deceived, to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, or anything which is signed or sealed, and which is capable of being converted into a valuable security, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.",
            "plain_language": "Equivalent to IPC Sec 420 — '420' style fraud inducing property/valuable security. BNS Sec 345 retains 7 years max + fine, cognizable, non-bailable.",
            "keywords": K("420 bns equivalent", "cheating property delivery", "345", "fraud"),
            "punishments": "Upto 7 years + fine",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "imprisonment_max_months": 84,
            "source_page": 372,
            "extra_data": {"maps_ipc_section": "420"},
        },
        {
            "act_short_title": "Bharatiya Nyaya Sanhita, 2023",
            "chapter": "CHAPTER 14 - OFFENCES RELATING TO MARRIAGE",
            "part": None,
            "section_number": "353",
            "title": "Sexual offences against nature",
            "bare_text": "Whoever, voluntarily has carnal intercourse against the order of nature with any woman, shall be punished with imprisonment of either description for a term which may extend to seven years and shall also be liable to fine. Explanation: Penetration is sufficient to constitute the carnal intercourse necessary to the offence described in this section.",
            "plain_language": "The BNS substantially narrows IPC Sec 377. BNS Sec 353 only applies to carnal intercourse against the order of nature WITH A WOMAN — thus DECRIMINALISING consensual same-sex penile-anal/oral intercourse with a man (already decriminalised in Navtej 2018, but the BNS codifies that limitation). Non-consensual acts with anyone and bestiality are covered under rape/aggravated sexual offence or separate bestiality provisions elsewhere. The BNS section applies only to the woman as victim and carries up to 7 years.",
            "keywords": K("bns 353", "377 narrowed", "against the order of nature woman only", "lgbtq codified decriminalisation", "navtej singh johar codified"),
            "punishments": "Upto 7 years + fine",
            "bailable": True,
            "cognizable": False,
            "compoundable": False,
            "imprisonment_max_months": 84,
            "source_page": 389,
            "extra_data": {"maps_ipc_section": "377 (narrowed)", "gender_limit": "victim must be woman"},
        },
    ],
    *[
        {
            "act_short_title": "Information Technology Act, 2000",
            "chapter": "CHAPTER XI - OFFENCES",
            "part": None,
            "section_number": "66",
            "title": "Computer related offences",
            "bare_text": "If any person, dishonestly or fraudulently, does any act referred to in section 43, he shall be punishable with imprisonment for a term which may extend to three years or with fine which may extend to five lakh rupees or with both.",
            "plain_language": "IT Act Sec 66 elevates the civil wrongs under Sec 43 (unauthorised access, virus, damage, denial of service, stolen computer resources, etc.) into CRIMINAL offences IF the acts are done DISHONESTLY or FRAUDULLY. Punishment is up to 3 years + ₹5 lakh fine.",
            "keywords": K("66 it act", "computer crime", "unauthorised access", "virus", "hacking", "dishonestly fraudulently"),
            "punishments": "Upto 3 years or ₹5L fine or both",
            "bailable": True,
            "cognizable": True,
            "compoundable": True,
            "imprisonment_max_months": 36,
            "fine_max": 500000,
            "source_page": 72,
            "extra_data": {"cross_refs": ["Sec 43 civil liability", "Sec 66A struck down (Shreya Singhal 2015)", "Sec 66B/66C/66D/66E/66F specific offences"]},
        },
        {
            "act_short_title": "Information Technology Act, 2000",
            "chapter": "CHAPTER XI - OFFENCES",
            "part": None,
            "section_number": "67",
            "title": "Punishment for publishing or transmitting obscene material in electronic form",
            "bare_text": "Whoever publishes or transmits or causes to be published or transmitted in the electronic form, any material which is lascivious or appeals to the prurient interest or if its effect is such as to tend to deprave and corrupt persons who are likely, having regard to all relevant circumstances, to read, see or hear the matter contained or embodied in it, shall be punished on first conviction with imprisonment of either description for a term which may extend to three years and with fine which may extend to five lakh rupees and in the event of second or subsequent conviction with imprisonment of either description for a term which may extend to five years and also with fine which may extend to ten lakh rupees.",
            "plain_language": "Publishes/transmits obscene electronic content (lascivious, prurient, tending to deprave): 3 years + ₹5L (first), 5 years + ₹10L (repeat). Sec 67A adds 'sexually explicit' content (min 7 years), Sec 67B adds child pornography (min 5 years / 7y repeat). Sec 69 & 69A provide blocking/surveillance powers with safeguards.",
            "keywords": K("67 it act", "obscene electronic", "67a sexually explicit", "67b child porn", "69a blocking"),
            "punishments": "First: 3y ₹5L; Repeat: 5y ₹10L",
            "bailable": True,
            "cognizable": True,
            "compoundable": False,
            "imprisonment_max_months": 60,
            "fine_max": 1000000,
            "source_page": 76,
            "extra_data": {"landmark": "Shreya Singhal v UOI struck down 66A (2015) — 66/67/67A/67B remain valid"},
        },
        {
            "act_short_title": "Information Technology Act, 2000",
            "chapter": "CHAPTER IX - INTERMEDIARIES NOT TO BE LIABLE IN CERTAIN CASES",
            "part": None,
            "section_number": "79",
            "title": "Exemption from liability of intermediary in certain cases",
            "bare_text": "(1) Notwithstanding anything contained in any law for the time being in force but subject to the provisions of sub-sections (2) and (3), an intermediary shall not be liable for any third-party information, data, or communication link made available or hosted by him. (2) The provisions of sub-section (1) shall apply if—(a) the function of the intermediary is limited to providing access to a communication system over which information made available by third parties is transmitted or temporarily stored or hosted; or (b) the intermediary does not—(i) initiate the transmission, (ii) select the receiver of the transmission, and (iii) select or modify the information contained in the transmission; (c) the intermediary observes due diligence while discharging his duties under this Act and also observes such other guidelines as the Central Government may prescribe in this behalf. (3) The provisions of sub-section (1) shall not apply if—(a) the intermediary has conspired or abetted in the commission of the unlawful act; or (b) upon receiving actual knowledge, or on being notified by the appropriate Government or its agency that any information, data or communication link residing in or connected to a computer resource controlled by the intermediary is being used to commit the unlawful act, the intermediary fails to expeditiously remove or disable access to that material on that resource without vitiating the evidence in any manner.",
            "plain_language": "IT Act Sec 79 is the 'safe harbour' for platforms (intermediaries): they are NOT liable for third-party content IF they are passive conduits, don't initiate/select/modify the transmission, AND conduct due diligence (per 2021 IT Rules: remove unlawful content within 36 hours of court/Govt order, publish grievance officers, appoint Chief Compliance/Nodal/Resident Grievance Officers, trace originator of messages if ordered). Loss of safe harbour under (3) if they conspire/abet, or fail to takedown after 'actual knowledge' or 'court/Govt notice'.",
            "keywords": K("79 it act", "safe harbour", "intermediary", "due diligence", "it rules 2021", "36 hour takedown", "shreya singhal"),
            "punishments": "Loss of safe harbour exposes intermediary to civil/criminal liability under applicable law",
            "bailable": None,
            "cognizable": None,
            "compoundable": None,
            "source_page": 94,
            "extra_data": {"linked_guideline": "Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021"},
        },
    ],
    *[
        {
            "act_short_title": "Protection of Women from Domestic Violence Act, 2005",
            "chapter": "CHAPTER I - PRELIMINARY",
            "part": None,
            "section_number": "3",
            "title": "Definition of domestic violence",
            "bare_text": "For the purposes of this Act, any act, omission or commission or conduct of the respondent shall constitute domestic violence in case it:—(a) harms or injures or endangers the health, safety, life, limb or well-being, whether mental or physical, of the aggrieved person or tends to do so and includes causing physical abuse, sexual abuse, verbal and emotional abuse and economic abuse; or (b) harasses, harms, injures or endangers the aggrieved person with a view to coerce her or any other person related to her to meet any unlawful demand for any dowry or other property or valuable security; or (c) has the effect of threatening the aggrieved person or any person related to her by any conduct mentioned in clause (a) or clause (b); or (d) otherwise injures or causes harm, whether physical or mental, to the aggrieved person.",
            "plain_language": "PWDVA Sec 3 defines 'domestic violence' expansively, covering 4 types of abuse recognized under the Act: (1) Physical abuse — bodily hurt/injury; (2) Sexual abuse — forced intercourse, sexual humiliations, etc.; (3) Verbal & Emotional abuse — insults, taunts, humiliation, threats of harm, especially regarding dowry or childlessness; (4) Economic abuse — taking away resources, restricting access to household necessities, dispossession of property, forced outings to earn. Also includes dowry harassment as in (b) and threats as in (c). This is a CIVIL statute — breach of a protection order IS a criminal offence under Sec 31 (1 year + fine).",
            "keywords": K("domestic violence definition", "pwdva 3", "physical abuse", "sexual abuse", "verbal emotional", "economic abuse", "dowry harassment"),
            "punishments": "Civil remedies (protection/residence/monetary/custody/compensation orders). Breach = Sec 31 1y imprisonment + fine.",
            "bailable": None,
            "cognizable": None,
            "compoundable": None,
            "source_page": 12,
            "extra_data": {"cross_ref": "IPC 498A criminal counterpart"},
        },
    ],
    *[
        {
            "act_short_title": "Prevention of Money Laundering Act, 2002",
            "chapter": "CHAPTER II - OFFENCE OF MONEY-LAUNDERING",
            "part": None,
            "section_number": "3",
            "title": "Offence of money-laundering",
            "bare_text": "Whosoever directly or indirectly attempts to indulge or knowingly assists or knowingly is a party or is actually involved in any process or activity connected with the proceeds of crime including its concealment, possession, acquisition or use and projecting or claiming it as untainted property shall be guilty of offence of money-laundering.",
            "plain_language": "PMLA Sec 3 criminalises any involvement (direct/indirect, attempt, assistance, knowing party) in ANY process that touches 'proceeds of crime' — including concealment, possession, acquisition, use, OR claiming/representing the property as clean/untainted. PMLA is unusual: it is an 'in rem' statute enabling attachment/confiscation of the tainted property itself (Sec 5(1) attachment by ED Director) even before trial; bail is extremely restricted post 2019 amendments (Sec 45 twin conditions for bail: prima facie case + unlikely to commit offence on bail + not tamper). SC in Vijay Madanlal Choudhary (2022) upheld most provisions with reading down.",
            "keywords": K("pmla 3", "money laundering", "proceeds of crime", "concealment possession acquisition use", "ed attachment", "sec 45 bail restrictions"),
            "punishments": "Sec 4: 3y to 10y rigorous + fine; Sec 4 EC/2019 adds fine upto 5% value of proceeds",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "imprisonment_min_months": 36,
            "imprisonment_max_months": 120,
            "source_page": 14,
            "extra_data": {"landmark": "Vijay Madanlal Choudhary v. Union of India (2022 SC 3-judge) reading down Sec 45 arrest safeguards"},
        },
        {
            "act_short_title": "Prevention of Money Laundering Act, 2002",
            "chapter": "CHAPTER II - OFFENCE OF MONEY-LAUNDERING",
            "part": None,
            "section_number": "4",
            "title": "Punishment for money-laundering",
            "bare_text": "Whoever commits the offence of money-laundering shall be punishable with rigorous imprisonment for a term which shall not be less than three years but which may extend to seven years and shall also be liable to fine which may extend to five lakh rupees. Provided that where the proceeds of crime involved in money-laundering relate to any offence specified under Part A of the Schedule [NDPS, Terrorism, Arms, etc.], the punishment shall be for the term which shall not be less than three years but may extend to ten years and shall also be liable to fine which may extend to five crore rupees.",
            "plain_language": "General PMLA sentence: minimum 3 years / maximum 7 years + up to ₹5L fine. For high-schedule offences (Part A: NDPS, UAPA/Terrorism, Arms Act, Explosive Substances, waging war, corruption, etc.): up to 10 years + up to ₹5 CRORE fine. The ED's power under Sec 5 to provisionally attach suspected tainted property for 180 days (extendable to 365 with ED Director approval) is a distinct civil mechanism that operates parallel to the criminal prosecution.",
            "keywords": K("pmla 4", "3 to 7 years", "part a schedule upto 10 years 5 crore", "ed attachment civil"),
            "punishments": "General: 3y-7y + ₹5L; Part A Schedule: 3y-10y + ₹5Cr",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "imprisonment_min_months": 36,
            "imprisonment_max_months": 120,
            "fine_max": 50000000,
            "source_page": 16,
            "extra_data": {"schedule_parts": ["Part A Scheduled Offences", "Part B ₹1Cr threshold", "Part C Cross-border"]},
        },
    ],
    *[
        {
            "act_short_title": "Scheduled Castes and Scheduled Tribes (Prevention of Atrocities) Act, 1989",
            "chapter": "CHAPTER II - OFFENCES OF ATROCITIES",
            "part": None,
            "section_number": "3",
            "title": "Punishments for offences of atrocities",
            "bare_text": "(1) Whoever, not being a member of a Scheduled Caste or a Scheduled Tribe,—(i) puts any inedible or obnoxious substance into the mouth of a member of a Scheduled Caste or a Scheduled Tribe or forces such member to drink or eat such inedible or obnoxious substance; ... shall be punishable with imprisonment for a term which shall not be less than six months but which may extend to five years and with fine. ... (2) Whoever, not being a member of a Scheduled Caste or a Scheduled Tribe,—(a) gives or fabricates false evidence intending thereby to cause, or knowing it to be likely that he will thereby cause, any member of a Scheduled Caste or a Scheduled Tribe to be convicted of an offence which is capital by the law for the time being in force shall be punished with imprisonment for life and with fine; ... (xi) assaults or uses force on any woman belonging to a Scheduled Caste or a Scheduled Tribe with intent to dishonour or outrage her modesty; ...",
            "plain_language": "SCST (POA) Sec 3 is a sprawling catalogue of caste-tinted atrocities, each punishable on conviction. KEY FEATURES: (1) Offender must be non-SC/non-ST; (2) Must be done by reason of the victim being SC/ST. Sec 3(1) common atrocities: 6m → 5y + fine. Sec 3(2) aggravated: fabricating capital-case evidence against SC/ST = LIFE IMPRISONMENT, gang rape of SC/ST woman = death or life imprisonment, atrocities by public servant = mandatory minimum 1 year, forcing stripping/parading naked = 3y-7y. Amendment 2015 added Sec 3(1)(va)(vii): social/economic boycott, tonsuring, garlanding with chappals. Amendment 2018 reinserted anticipatory-bail bar struck down by SC in Dr. Subhash Kashinath Mahajan (2018); SC upheld 2018 amendment in Prathvi Raj Chauhan (2020) adding preliminary enquiry prior to FIR and senior officer approval for arrest to prevent misuse.",
            "keywords": K("scst act 1989 3", "poa", "atrocity", "caste", "anticipatory bail barred prathvi raj 2020", "public servant min 1y", "gang rape death life"),
            "punishments": "Sec 3(1) common: min 6m → 5y + fine; Sec 3(2) aggravated: life or death; Sec 3(2)(v) gang rape SCST woman = death or life",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "life_imprisonment": True,
            "death_penalty": True,
            "imprisonment_min_months": 6,
            "imprisonment_max_months": 60,
            "source_page": 19,
            "extra_data": {"landmarks": ["Dr. Subhash Kashinath Mahajan (2018 SC)", "Prathvi Raj Chauhan v. UOI (2020 SC upholds 2018 Amendments)"]},
        },
        {
            "act_short_title": "Scheduled Castes and Scheduled Tribes (Prevention of Atrocities) Act, 1989",
            "chapter": "CHAPTER II - OFFENCES OF ATROCITIES",
            "part": None,
            "section_number": "4",
            "title": "Punishment for neglect of duties",
            "bare_text": "Whoever, being a public servant but not being a member of a Scheduled Caste or a Scheduled Tribe, wilfully neglects his duties required to be performed by him under this Act, shall be punishable with imprisonment for a term which shall not be less than six months but which may extend to one year.",
            "plain_language": "SCST Act Sec 4 holds non-SC/ST public servants CRIMINALLY liable for WILLFUL NEGLECT of duties under the Act. This includes delaying FIR registration, refusing to register SC/ST victim complaints, delaying medical treatment, neglecting the POA Rules 1995 timeframes (e.g., investigation within 60 days, charge sheet within same period). Punishment: mandatory 6 months minimum to maximum 1 year.",
            "keywords": K("scst act 4", "public servant neglect", "wilful neglect", "duties of police", "6 months minimum"),
            "punishments": "Min 6m → 1 year",
            "bailable": False,
            "cognizable": True,
            "compoundable": False,
            "imprisonment_min_months": 6,
            "imprisonment_max_months": 12,
            "source_page": 35,
            "extra_data": {"poa_rules": ["Rule 7(1) FIR immediately", "Rule 12(6) investigation charge sheet 60 days", "Rule 15 victim compensation"]},
        },
    ],
]
